93 scs rainfall curve back end
Deltares/FloodAdapt pull request #147
Opened 2023-07-04 09:52 UTC by GundulaW

2023-07-04 15:18 UTC, GundulaW commented
Added rainfall shapes including SCS rainfall curves in the back-end. 

The following tests are still failing but Tim has fixed these in the hurricane branch:

- test_object_mode\test_events\test_download_meteo
- test_object_mode\test_integrator\test_preprocess_rainfall_timeseries --> was working when Tim checked out my branch but we used the same hydromt versions

2023-07-04 15:22 UTC, GundulaW commented
I also had to made some changes to event and hazard.py related to event_sets

2023-07-06 12:26 UTC, panosatha commented on flood_adapt/object_model/hazard/event/event.py
> +    ) -> np.ndarray:
could you write some doc strings in the functions in this class?

2023-07-06 12:38 UTC, panosatha commented on flood_adapt/object_model/hazard/event/synthetic.py
> +            surge = super().timeseries_shape(
why do you need to use super() here? self wouldn't work?

2023-07-06 13:01 UTC, panosatha commented on tests/test_database/charleston/static/site/scs_rainfall.csv
I would put this in a seperate "rainfall_curves" folder in the static data folder

2023-07-06 13:12 UTC, panosatha requested changes
Great work! I made some minor comments that you can have a look before merging.

2023-07-06 15:36 UTC, GundulaW commented on .gitignore
> +tests/test_database/charleston/input/events/
removed this

2023-07-06 15:52 UTC, merged